
spring:
  application:
    name: @project.name@
  security:
    user:
      name: admin
      password: password
      roles:
        - ADMIN
        - USER
        - GUEST

logging:
  level:
    org:
      springframework:
        security: TRACE
